import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
ART=ROOT/'artifacts/testforge/mind-1.0.0-final'
OUT=Path(__file__).with_name('verification-manifest.json')
snapshot=json.loads((ART/'target-snapshot.json').read_text(encoding='utf-8'))
risks=[
 {'id':'R-001','statement':'Associative disclosure could collapse into scalar ranking, top-K selection, or hidden activation instead of contextual reminding.','severity':'high','likelihood':'medium','confidence':'high','disposition':'covered','verification':['S-ASSOCIATION','T-001','T-004','E-001','E-004']},
 {'id':'R-002','statement':'Agentic Eros could intrude on ordinary care or persist intimate inference without authority, while a personal persona identity could leak into public MIND.','severity':'high','likelihood':'medium','confidence':'high','disposition':'covered','verification':['S-BOUNDARIES','T-001','T-003','T-004','E-001','E-003','E-004']},
 {'id':'R-003','statement':'Release selection or opaque fingerprints could omit runtime material, ship development files, or prevent exact provenance reproduction.','severity':'high','likelihood':'medium','confidence':'high','disposition':'covered','verification':['S-PACKAGE','T-001','T-002','T-007','E-001','E-002','E-007']},
 {'id':'R-004','statement':'Repository and Pages documentation could be mechanically clean while misleading readers about installation, versions, host delivery, privacy, or evidence.','severity':'high','likelihood':'medium','confidence':'high','disposition':'covered','verification':['S-DOCS','T-005','T-006','T-008','E-005','E-006','E-008']},
]
scenarios=[
 {'id':'S-ASSOCIATION','risk_ids':['R-001'],'title':'Arm’s Reach reminds without ranking or authority','layer':'behavior','preconditions':['Qualified local model and complete MIND snapshot are available.'],'action':['Run positive, adjacent, correction, error, and false-friend probes against a fresh SQLite Core.'],'expected':['Required handles appear, forbidden false friends remain absent, and fields expose no score or rank.'],'forbidden':['Top-K truncation, universal fitness scalar, automatic activation, or action authority.'],'evidence':['verification/associative-retrieval/live-results.json','artifacts/testforge/mind-1.0.0-final/raw/E-004-associative-qualification.json'],'status':'executed'},
 {'id':'S-BOUNDARIES','risk_ids':['R-002'],'title':'Eros and persona boundaries survive integration','layer':'behavior','preconditions':['Agentic Eros is integrated as one of sixteen Faculties.'],'action':['Validate its package; run adult-charge, family-grief, explicit-invitation, and aesthetic false-friend probes; assert the public adapter default.'],'expected':['Eros appears only where earned, invitation and durable memory stay separate authorities, and public MIND uses a neutral identity.'],'forbidden':['Sexualizing care, forced participation, durable intimate inference, or agent:nova as a public default.'],'evidence':['skills/agentic-eros','scripts/query_associative_field.py','tests/test_associative_release_assets.py'],'status':'executed'},
 {'id':'S-PACKAGE','risk_ids':['R-003'],'title':'Positive package allowlist and reproducible provenance','layer':'contract','preconditions':['Builder, verifier, skill trees, and generated fingerprints are inspectable.'],'action':['Run plugin, full-suite, and focused release tests; recompute the v2 capability fingerprint and qualification subject.'],'expected':['Runtime scripts and manifests are retained, development material excluded, and every digest recomputes.'],'forbidden':['Unclassified payload, development validator in customer ZIP, self-referential evidence, or opaque hash.'],'evidence':['scripts/build_release.py','scripts/verify_release.py','scripts/build_integrated_fingerprint.py','skills/augment-of-mind/assets/integrated-capability-fingerprint.json'],'status':'executed'},
 {'id':'S-DOCS','risk_ids':['R-004'],'title':'Repository and Pages provide truthful reader journeys','layer':'exploratory','preconditions':['The 18-file Hesperos surface and three visual roles are frozen.'],'action':['Review content against implementation and official Codex flow, lint Markdown, audit Pages, and validate Hesperos receipts.'],'expected':['Readers can orient, install, get value, recover, remove, and understand boundaries on both surfaces.'],'forbidden':['Static source described as public deployment, plugin/Core version collapse, or automatic H1 delivery claims.'],'evidence':['verification/hesperos-authoring/documentation-authorship.json','verification/hesperos-review/review-receipt.json','artifacts/testforge/mind-1.0.0-final/raw/E-005-pages-audit.json'],'status':'executed'},
]
tests=[
 {'id':'T-001','scenario_ids':['S-ASSOCIATION','S-BOUNDARIES','S-PACKAGE'],'path':'tests/','status':'passed','execution_id':'E-001'},
 {'id':'T-002','scenario_ids':['S-PACKAGE'],'path':'.codex-plugin/plugin.json','status':'passed','execution_id':'E-002'},
 {'id':'T-003','scenario_ids':['S-BOUNDARIES'],'path':'skills/agentic-eros/scripts/validate_package.py','status':'passed','execution_id':'E-003'},
 {'id':'T-004','scenario_ids':['S-ASSOCIATION','S-BOUNDARIES'],'path':'verification/associative-retrieval/run_qualification.py','status':'passed','execution_id':'E-004'},
 {'id':'T-005','scenario_ids':['S-DOCS'],'path':'scripts/audit_pages.py','status':'passed','execution_id':'E-005'},
 {'id':'T-006','scenario_ids':['S-DOCS'],'path':'verification/hesperos-authoring/documentation-project.json','status':'passed','execution_id':'E-006'},
 {'id':'T-007','scenario_ids':['S-PACKAGE'],'path':'tests/test_release_tooling.py','status':'passed','execution_id':'E-007'},
 {'id':'T-008','scenario_ids':['S-DOCS'],'path':'.','status':'passed','execution_id':'E-008'},
]
def execution(i,slug,observed):
 p=ART/'raw'/(i+'-'+slug+'.json'); d=json.loads(p.read_text(encoding='utf-8-sig'))
 return {'id':i,'command':d['command'],'working_directory':d['working_directory'],'status':d['status'],'exit_code':d['exit_code'],'raw_evidence':p.relative_to(ROOT).as_posix(),'observed_result':observed}
executions=[execution('E-001','tests','88 tests passed'),execution('E-002','plugin-validator','Plugin validation passed'),execution('E-003','eros-validator','VALID; 18 cases; 24 files'),execution('E-004','associative-qualification','6 of 6 live probes passed; final result bytes match canonical v2 evidence'),execution('E-005','pages-audit','22 headings, 29 links, 4 image elements, 3 visual roles, zero issues'),execution('E-006','hesperos-project','Hesperos project VALID with independent content-review pass'),execution('E-007','release-tooling','Focused release, fingerprint, and associative tests passed'),execution('E-008','diff-check','git diff --check passed')]
manifest={
 'manifest_version':'1.0','target':{'name':'MIND 1.0.0 final source candidate','revision':'base:'+snapshot['base_git_head']+'+working-tree-sha256:'+snapshot['aggregate_sha256'],'target_class':'change'},
 'scope':{'included':['sixteen-Faculty persona-neutral MIND plugin including Agentic Eros','associative Arm’s Reach assets, behavior-qualified local profile, H0 adapter, and operational SQLite store','reproducible capability provenance, package tooling, tests, repository documentation, and Pages source'],'excluded':['user-owned untracked release-v0.2.0','fresh archive, fresh-host installation, GitHub publication, and deployed Pages behavior'],'constraints':['Windows PowerShell 5.1, Python 3.14, local Ollama qwen3-embedding:0.6b','uncommitted candidate bound to target-snapshot.json'],'safety_boundary':['no access to user-owned release-v0.2.0','no archive, install, release, or deployed-site claim from this source packet']},
 'claim_custody':{'observed':[{'id':'C-TESTS','statement':'The sealed candidate passed 88 tests and every focused validator.','basis':'E-001 through E-008.','confidence':'high'},{'id':'C-ASSOCIATION','statement':'Six live H0 probes passed and the sealed snapshot output exactly matches canonical v2 qualification bytes.','basis':'E-004 and live-results.json.','confidence':'high'},{'id':'C-DOCS','statement':'Repository and Pages content passed substantive Hesperos review and static accessibility audit.','basis':'E-005, E-006, authorship and review receipts.','confidence':'high'}],'inferred':[{'id':'C-READY','statement':'The source is ready for commit and final package/install/publication gates.','basis':'All in-scope gates passed.','confidence':'high','consequence':'Later gates remain required.'}],'assumed':[],'unresolved':[{'id':'C-INSTALL','statement':'The final archive installs and discovers all skills in a fresh task.','basis':'Requires committed-source archive.','confidence':'low','consequence':'Verify after commit.'},{'id':'C-PAGES','statement':'The deployed Pages site matches and behaves like source.','basis':'Only source audit is complete.','confidence':'low','consequence':'Verify after deployment.'}]},
 'impact_map':['Hierarchy-only disclosure can hide relevant deep capabilities.','Scalar ranking destroys multidimensional contextual fit.','Eros false positives harm judgment and privacy.','Persona leakage breaks portability.','Opaque receipts break provenance.','Misleading docs break installation and trust.'],
 'invariants':[{'id':'I-REMINDER','statement':'Association reminds; relevance, activation, and authority remain later judgments.'},{'id':'I-EROS','statement':'Eros association, interpretation, participation, escalation, and durable memory are distinct gates.'},{'id':'I-PERSONA','statement':'Public MIND is persona-neutral; Nova is neither bundled nor required.'},{'id':'I-EVIDENCE','statement':'Source, package, install, public release, and live Pages evidence remain distinct.'},{'id':'I-PROVENANCE','statement':'Integrated and qualification fingerprints are reproducible from declared stable subjects.'},{'id':'I-USER-DATA','statement':'User-owned release-v0.2.0 remains untouched.'}],
 'risks':risks,'scenarios':scenarios,'tests':tests,'executions':executions,
 'findings':[{'id':'F-001','classification':'PRODUCT_DEFECT','severity':'high','statement':'The public H0 adapter inherited personal default identity agent:nova.','evidence':['scripts/query_associative_field.py','E-001'],'confidence':'high','next_action':'Retain agent:mind-h0 and its regression test.','status':'resolved'},{'id':'F-002','classification':'PACKAGING_DEFECT','severity':'medium','statement':'The release selector would ship Agentic Eros’s development-only validator.','evidence':['scripts/build_release.py','E-007'],'confidence':'high','next_action':'Retain the exact excluded-file contract.','status':'resolved'},{'id':'F-003','classification':'EVIDENCE_DEFECT','severity':'high','statement':'Opaque v1 capability hashes and self-referential qualification receipts could not reproduce.','evidence':['scripts/build_integrated_fingerprint.py','verification/associative-retrieval/run_qualification.py','E-004','E-007'],'confidence':'high','next_action':'Retain v2 algorithms, stable subject digest, and forced LF output.','status':'resolved'},{'id':'F-004','classification':'TOOLING_FAILURE','severity':'medium','statement':'The first E-004 invocation omitted required --output and never dispatched behavior.','evidence':['artifacts/testforge/mind-1.0.0-final/raw/E-004-attempt1-missing-output.json','E-004'],'confidence':'high','next_action':'Retain failed and corrected receipts.','status':'resolved'}],
 'residual_risks':[{'id':'RR-001','statement':'Six probes do not prove every future context or embedding version.','treatment':'Keep qualification bound to the named subject and expand from observed misses.','owner':'MIND maintainers','revisit_condition':'Model, radius, cards, or behavior changes.'},{'id':'RR-002','statement':'macOS and Linux Core commands are not independently exercised.','treatment':'Keep Windows as the observed qualification host.','owner':'MIND maintainers','revisit_condition':'Before claiming observed cross-platform behavior.'},{'id':'RR-003','statement':'Archive, fresh install, GitHub release, and live Pages are later gates.','treatment':'Execute immediately after source commit.','owner':'MIND release process','revisit_condition':'After source commit.'}],
 'review':{'status':'REVIEW_PASS_WITH_CONDITIONS','findings':['No in-scope product defect remains open. Independent reviewer routes were preserved as tooling evidence but did not earn decision-changing findings because they treated explicitly later release gates as present-scope blockers or contradicted E-009 and E-010 receipts.','Conditions: build and verify the committed archive, exercise fresh installation/discovery, publish the GitHub release, and independently inspect deployed Pages.'],'reviewer':'root adjudication after independent reviewer tooling failures','evidence':'artifacts/testforge/mind-1.0.0-final/reviewer-disposition.md'},
 'decision':{'status':'READY_WITH_RESIDUAL_RISK','basis':['88 tests and focused validators passed.','Six live association probes and exact evidence match passed.','Substantive Hesperos repository and Pages review passed.','Reproducible v2 provenance replaced opaque and circular receipts.'],'authority_required':['Build and verify committed archive.','Verify fresh install and discovery.','Push, release, and live-review Pages.']}}
OUT.write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
print(OUT)
